In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [ ]:
df = pd.read_csv('spam.csv')

In [ ]:
df.head(5)

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [ ]:
df.Category.value_counts()

,count
Category,
ham,4825
spam,747


In [ ]:
df.Category.value_counts()/len(df)*100

,count
Category,
ham,86.593683
spam,13.406317


In [ ]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [ ]:
df.head(5)

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [ ]:
df.shape

(5572, 3)

#### **Train Test Split**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam,test_size=0.2)

In [ ]:
X_train.shape

(4457,)

In [ ]:
X_test.shape

(1115,)

In [ ]:
X_train[:4]

,Message
4156,Want a new Video Phone? 750 anytime any networ...
1888,Urgent! Please call 09061743811 from landline....
640,I had askd u a question some hours before. Its...
2311,You have won a Nokia 7250i. This is what you g...


In [ ]:
y_train[:4]

,spam
4156,1
1888,1
640,0
2311,1


#### **Create bag of words representation using CountVectorizer**

In [ ]:
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_test_cv = v.transform(X_test)

In [ ]:
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59371 stored elements and shape (4457, 7828)>

In [ ]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
X_train_cv.shape

(4457, 7828)

In [ ]:
v.get_feature_names_out()[1750]

'charge'

In [ ]:
v.vocabulary_

{'want': 7455,
 'new': 4818,
 'video': 7361,
 'phone': 5239,
 '750': 631,
 'anytime': 1009,
 'any': 1001,
 'network': 4809,
 'mins': 4554,
 'half': 3344,
 'price': 5462,
 'line': 4188,
 'rental': 5766,
 'free': 3023,
 'text': 6857,
 'for': 2977,
 'months': 4637,
 'reply': 5777,
 'or': 5025,
 'call': 1619,
 '08000930705': 49,
 'delivery': 2259,
 'urgent': 7280,
 'please': 5303,
 '09061743811': 197,
 'from': 3060,
 'landline': 4061,
 'your': 7796,
 'abta': 783,
 'complimentary': 1957,
 'tenerife': 6838,
 'holiday': 3515,
 '5000': 545,
 'cash': 1689,
 'await': 1176,
 'collection': 1913,
 'sae': 5937,
 'cs': 2119,
 'box': 1467,
 '326': 449,
 'cw25wx': 2161,
 '150ppm': 306,
 'had': 3335,
 'askd': 1104,
 'question': 5591,
 'some': 6357,
 'hours': 3560,
 'before': 1300,
 'its': 3820,
 'answer': 992,
 'you': 7790,
 'have': 3398,
 'won': 7658,
 'nokia': 4861,
 '7250i': 626,
 'this': 6921,
 'is': 3800,
 'what': 7554,
 'get': 3159,
 'when': 7560,
 'win': 7603,
 'our': 5060,
 'auction': 1148,
 'to

In [ ]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
np.where(X_train_np[0]!=0)

(array([  49,  631, 1001, 1009, 1619, 2259, 2977, 3023, 3344, 4188, 4554,
        4637, 4809, 4818, 5025, 5239, 5462, 5766, 5777, 6857, 7361, 7455]),)

#### **Naive Bayes Classifier**

In [ ]:
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [ ]:
y_pred = model.predict(X_test_cv)

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       965
           1       0.97      0.95      0.96       150

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



#### **Test on a random datapoint**

In [ ]:
message = {"Want a new Video Phone?"}


In [ ]:
message_cnt = v.transform(message)

model.predict(message_cnt)

array([1])