In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
df = pd.read_csv('50_Startups.csv')

FileNotFoundError: [Errno 2] No such file or directory: '50_Startups.csv'

In [ ]:
df.head()

In [ ]:
df.info()

NameError: name 'df' is not defined

In [ ]:
df.describe()


In [ ]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values


In [ ]:
X

In [ ]:
y

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
X

array([[-0.12558017, -1.25695187],
       [-0.94619938,  0.30456086],
       [ 0.76048352,  0.12115275],
       [ 0.69326299, -1.75202878],
       [-0.96167156,  0.45942015],
       [ 0.54934005,  0.64859416],
       [-0.08376475,  0.21428361],
       [ 0.59352597,  0.49418049],
       [ 0.0339483 ,  0.16793174],
       [ 0.56155886, -1.46528653],
       [-1.63878432, -0.41473988],
       [-0.45252963, -0.3614373 ],
       [ 0.67678187,  0.28732109],
       [-1.41275459,  1.05020337],
       [-0.99132985,  0.2364205 ],
       [ 1.097628  , -0.44532876],
       [ 0.1485175 , -0.86129211],
       [ 0.22236232, -0.19520543],
       [ 0.01516893,  0.3256156 ],
       [-0.24707983,  1.03197509],
       [ 0.62853964,  0.69984648],
       [ 1.34425513, -0.78412953],
       [-0.88435108, -1.40294757],
       [ 0.28607217,  0.9512744 ],
       [-2.39243205, -1.46252508],
       [ 0.17592267, -0.40548682],
       [-0.83508468, -0.86086689],
       [-0.53710789, -0.53153082],
       [-1.30727914,

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
len(X_train)

80

In [ ]:
len(X_test)

20

In [ ]:
X_test

array([[ 0.1485175 , -0.86129211],
       [ 1.1389118 , -0.09651294],
       [-0.08376475,  0.21428361],
       [ 0.96219795, -0.29697022],
       [-0.87364211,  0.64192784],
       [-0.79223135,  0.00312749],
       [-0.35416776,  0.67374536],
       [ 1.34425513, -0.78412953],
       [ 1.04629211, -0.142033  ],
       [-0.86174837,  0.03241832],
       [ 1.00454395, -0.0088866 ],
       [-2.39243205, -1.46252508],
       [-0.96167156,  0.45942015],
       [-1.87255226, -0.14813832],
       [-0.88435108, -1.40294757],
       [-0.93208637, -1.37553593],
       [ 0.55653162, -0.69283054],
       [ 0.22236232, -0.19520543],
       [ 1.1597378 , -0.43141546],
       [ 1.20547931,  0.93005741]])

In [ ]:
y_test

array([ -42.5796566 ,   22.80134902,  -15.7950762 ,    6.95874546,
         54.56499889,   46.43122555,   53.54681635,   22.24375407,
         19.2096481 ,  -77.93550365,   38.07134443, -159.00618192,
         -3.18933994, -123.58256628, -115.66880492, -118.33613758,
       -121.78431932,   38.17272092,   -2.60451056,   27.14672348])

In [ ]:
y_train

array([  -2.66010285,  108.76459577,   60.17849025,   38.83510492,
        106.62873679,  130.09888713,   89.60431527,  127.50148349,
        -54.19738865,   -2.91891057,   22.66155048,   58.53832351,
        -17.59673644, -124.79351975,   34.99008331,  -32.25145983,
         32.63224342,  -53.18964017, -162.03721191,  -33.43111355,
         97.08287911,   42.56634352,  -25.41770733,   10.93471469,
       -147.03665314,  -52.06998805,  -89.35933886,   81.44951374,
         -3.60405451, -112.87914601,   54.7403578 ,   39.63254755,
        120.59899719,   42.6404806 ,   72.10528595,  102.46244709,
         -2.9505287 ,   19.66312494,   -2.37694423,   -2.79705429,
        -53.97823806, -134.6273032 ,   49.55024603,   22.59711227,
        -81.07174134,   69.76833279,  -62.31073809,  -44.70352981,
         26.11087721,  110.76906324,   27.56924436,  -21.94137427,
       -178.45449337,   -5.00775159,  -28.44718266,   62.71172704,
        -17.75830021, -105.00381842,   69.23475012,   61.40015

In [ ]:
   from sklearn.preprocessing import StandardScaler
   sc = StandardScaler()
   X_train = sc.fit_transform(X_train)
   X_test = sc.fit_transform(X_test)

In [ ]:
X_test

array([[ 0.19406162, -0.91715183],
       [ 1.11143545,  0.22500057],
       [-0.02109476,  0.68915682],
       [ 0.94775048, -0.0743705 ],
       [-0.75273549,  1.32781815],
       [-0.67732704,  0.37380765],
       [-0.2715613 ,  1.37533574],
       [ 1.30163908, -0.80191408],
       [ 1.02564449,  0.15701906],
       [-0.74171866,  0.41755178],
       [ 0.98697437,  0.35586533],
       [-2.15954703, -1.81505767],
       [-0.83427464,  1.05525372],
       [-1.67799731,  0.14790113],
       [-0.76265491, -1.72608219],
       [-0.80687073, -1.68514453],
       [ 0.5719934 , -0.66556445],
       [ 0.26246197,  0.07760918],
       [ 1.13072598, -0.27515651],
       [ 1.17309502,  1.75812261]])

In [ ]:
#implement LR

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred = regressor.predict(X_test)

In [ ]:
plt.plot(y_pred,color='blue')
plt.plot(y_test,color='red')
plt.show()

NameError: name 'plt' is not defined

In [ ]:
dt = [[1.0, 0.0, 0.0, 80000, 125000, 250000]]


In [ ]:
new_df  = pd.DataFrame(dt)

In [ ]:
new_df = sc.transform(new_df)

ValueError: X has 6 features, but StandardScaler is expecting 2 features as input.

In [ ]:
new_df

In [ ]:
regressor.predict(new_df)

In [ ]:
from sklearn.datasets import make_regression
import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
X,y = make_regression(n_samples=100,n_features=2,n_informative=2,n_targets=1,noise=50)

In [ ]:
df = pd.DataFrame({'feauture1':X[:,0],'feauture2':X[:,1],'target':y})

In [ ]:
df.head()

feauture1  feauture2      target
0   0.236091   0.152404   -4.914074
1  -0.453320  -1.868399 -171.967821
2  -1.203289   1.794933  126.917690
3  -1.754017   1.054239   85.521305
4  -0.187716   1.019960   85.436131

In [ ]:
df.shape

(100, 3)

In [ ]:
fig  = px.scatter_3d(df, x="feauture1", y="feauture2", z="target")
fig.show()

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
y_pred

array([ -68.48768985,   65.36390889,   94.09285272,   35.53019662,
         76.25353179,   14.21604596,  138.35482531,   10.24483462,
         67.34265473,   31.12099522,    7.85394528,  -92.06939651,
       -121.90083458, -104.2293382 , -133.34658184,   81.37317309,
         85.22550814,  106.79465707,   71.75298697,  -53.09950569])

In [ ]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred)))

print("R2",r2_score(y_test,y_pred))

MAE 38.18532632341204
MSE 2156.1923670453166
RMSE 46.434818477574744
R2 0.7140736742987429


In [ ]:
import numpy as np
np.linspace(-3,-3,200).reshape(200,1)


array([[-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
       [-3.],
      